### Numpy basics

- arrays: vectors and matrices
- slicing



In [4]:
import numpy as np

#### Arrays

In [5]:
# an array is a collection of numbers
np.array([3, 7, 1, 8, 3, 9])

array([3, 7, 1, 8, 3, 9])

#### Vectors

In [6]:
# a vector is an array where the elements are arranged in a single row
v = np.array([3, 7, 1, 8, 3, 9])
v

array([3, 7, 1, 8, 3, 9])

In [7]:
# length of a vector
len(v)

6

In [8]:
# shape of a vector
v.shape

(6,)

In [9]:
# get an element from a vector
v[3]

8

In [10]:
# set an element of a vector
v[3] = 12
v

array([ 3,  7,  1, 12,  3,  9])

#### Matrices

In [11]:
# a matrix is an array where the elements are arranged in several rows (or rows and columns)
m = np.array([[3, 7, 1], [8, 3, 9]])
m

array([[3, 7, 1],
       [8, 3, 9]])

In [12]:
# length of a matrix (!!)
len(m)

2

In [13]:
# size of a matrix: total number of elements
m.size

6

In [14]:
# shape of a matrix
m.shape

(2, 3)

In [15]:
# number of rows
m.shape[0]

2

In [16]:
# number of columns
m.shape[1]

3

In [17]:
# get an element of a matrix: (row, column) coordinates
m[1, 0]

8

In [18]:
# set an element of a matrix
m[1, 0] = 25
m

array([[ 3,  7,  1],
       [25,  3,  9]])

#### slicing

In [19]:
# vector
v

array([ 3,  7,  1, 12,  3,  9])

In [20]:
# front slice
v[:3]

array([3, 7, 1])

In [21]:
# back slice
v[-2:]

array([3, 9])

In [22]:
# matrix
m

array([[ 3,  7,  1],
       [25,  3,  9]])

In [23]:
# row slicing
m[1, :]

array([25,  3,  9])

In [24]:
m[1]

array([25,  3,  9])

In [25]:
# column slicing
m[:, 2]

array([1, 9])

In [26]:
# slice
m[1:, 1:]

array([[3, 9]])

In [31]:
m2 = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])
m2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [41]:
# Per files i columnes
m2[1:3, 1:3]

array([[ 6,  7],
       [10, 11]])

In [47]:
print(m2[1:4, 1:4])

print(m2[1::, 1::])

[[ 6  7  8]
 [10 11 12]
 [14 15 16]]
[[ 6  7  8]
 [10 11 12]
 [14 15 16]]


In [46]:
m2[0,2]

3

#### iterate on vectors/matrices

In [28]:
for x in v: print(x)

3
7
1
12
3
9


In [25]:
for row in m: print(row)

[3 7 1]
[25  3  9]


In [26]:
for row in m:
    print(row)
    for x in row:
        print(x)

[3 7 1]
3
7
1
[25  3  9]
25
3
9


#### iterate using indexes

In [57]:
print(m)
print()
print(m.shape)
print()

for column_index in range(m.shape[1]): 
    print("i =",column_index)
    print(m[:, column_index])
    print()

[[ 3  7  1]
 [25  3  9]]

(2, 3)

i = 0
[ 3 25]

i = 1
[7 3]

i = 2
[1 9]



In [80]:
# Treure files i columnes de la  matriu anterior 
print("matriu: \n", m2)

print()
for column_index in range(m2.shape[1]): 
    if column_index > 1:
        print(m2[:, column_index])

print()
print(m2[:,2::])

print()
for column_index in range(2, m2.shape[1]): 
    print(m2[:, column_index])

matriu: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[ 3  7 11 15]
[ 4  8 12 16]

[[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]]

[ 3  7 11 15]
[ 4  8 12 16]


In [82]:
# Iterar per cada element de una matriu però tinguent amb compte les files i les columnes pas a pas
print(m)
print()

for colIdx in range(m.shape[1]):
    print(m[:, colIdx])
    for rowIdx in range(m.shape[0]):
        print(m[rowIdx, colIdx])

[[ 3  7  1]
 [25  3  9]]

[ 3 25]
3
25
[7 3]
7
3
[1 9]
1
9


In [90]:
# Ara el revés, iterar primer per les files i després imprimir les columnes
print(m)

print()
for rowIdx in range(m.shape[0]):
    print(m[rowIdx, :])
    for colIdx in range(m.shape[1]):
        print(m[rowIdx, colIdx])
    print()

[[ 3  7  1]
 [25  3  9]]

[3 7 1]
3
7
1

[25  3  9]
25
3
9

