#### Numpy basics 2
- most common numpy functions

In [1]:
import numpy as np

#### array generation functions

In [2]:
# initialize array with zeros
np.zeros(10) # floats de 64 bits

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
# initialize arrays with ones
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [28]:
# range array
np.arange(12)

[2 3 4 5]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [29]:
# rang
np.arange(2,6)

array([2, 3, 4, 5])

Fa un span del rang amb tants punts com li especifiquem

In [32]:
# span array
np.linspace(-1, 1, 21)

array([-1. , -0.9, -0.8, -0.7, -0.6, -0.5, -0.4, -0.3, -0.2, -0.1,  0. ,
        0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ])

In [31]:
len(np.linspace(-1,1,21))

21

In [35]:
np.linspace(1, 10, 7) # 7 punts

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. ])

In [39]:
np.linspace(100, 200, 101) # Si vols dividir un segment amb dos trosos, necesites tres punts, si vols 3 trosos, necesites 4
# haurem de posar un tros més

array([100., 101., 102., 103., 104., 105., 106., 107., 108., 109., 110.,
       111., 112., 113., 114., 115., 116., 117., 118., 119., 120., 121.,
       122., 123., 124., 125., 126., 127., 128., 129., 130., 131., 132.,
       133., 134., 135., 136., 137., 138., 139., 140., 141., 142., 143.,
       144., 145., 146., 147., 148., 149., 150., 151., 152., 153., 154.,
       155., 156., 157., 158., 159., 160., 161., 162., 163., 164., 165.,
       166., 167., 168., 169., 170., 171., 172., 173., 174., 175., 176.,
       177., 178., 179., 180., 181., 182., 183., 184., 185., 186., 187.,
       188., 189., 190., 191., 192., 193., 194., 195., 196., 197., 198.,
       199., 200.])

#### random integer arrays

In [46]:
# array of random integers between a given range
np.random.randint(1, 6, 10) # 10 tirades de dau diferents

array([2, 1, 2, 2, 1, 5, 5, 5, 4, 2])

### Proccesos estocastics
- Proccès que hi ha una certa aletorietat. 
- Les coses corresponen a una certa probabilitat. 
- Les coses no es poden determinar al 100%.

### procesos determistics
- Si sempre tens un input sempre tindras el mateix output.
- Podem determinar com funciona, donada una entrada, podem predir la sortida.

1. El que volem fer amb IA, és modelitzar proccesos, que en si són deterministics (predir temperatura) el clima obeix a unes condicions físiques (la natura oveix aquestes lleis). 

2. La majoría de vegades els sistemes són tant complexes (com el clima) hi entren tantes variables que acaba siguent impossible fer una predicció deterministica, són sistemes complexes.

3. Aquests sistemes es tracten estocasticament (amb probabilitat). Les prediccions tenen una certa probabilitat asociada no són 100% exactes. 

``Un ordinador, executa una seqüència lògica, són 0 i 1, hauríem de poder determinar la sortida, per definició és tot determinista``

Com pot ser que existeixi el ``randint`` &rarr; Pots predir la sortida del metode, no és aleatori 100%. 

In [60]:
#np.random.seed(2345) # Si la fixem sempre sortirà el mateix
np.random.randint(1,6,10)

array([1, 3, 1, 4, 2, 3, 4, 1, 3, 4])

##### Ex. binary array fo size 20

In [63]:
np.random.randint(0, 2, 20)

array([0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1])

#### random float arrays

In [7]:
# array of random floats in the half-open interval [0, 1) (0 <= x < 1)
np.random.rand(4)

array([0.80566894, 0.58009891, 0.52379074, 0.72216026])

In [70]:
# array of random numbers such that 0 <= x < 10
np.random.rand(10) *10

array([7.52987512, 9.11041522, 8.3200959 , 9.63352644, 7.83074111,
       8.00817724, 2.19547772, 3.74302061, 9.67938349, 6.11470745])

### range(1,10)
Array of random numbers such that 1 <= x < 10

In [71]:
np.random.rand(10)

array([0.34294253, 0.11076002, 0.93890696, 0.92979875, 0.59061872,
       0.50167879, 0.65813965, 0.4499934 , 0.29864814, 0.00204729])

In [104]:
np.random.rand(10) * (10 - 1) # 9 = el que medeix l'interval i a ++ quan val 0 al (0,1) volem que equivalqui a 1 (per això suma 1 a baix)
# np.random(10) * (10 - 0) + 0

array([3.20477024, 8.48067016, 1.42760029, 6.58266437, 8.98184197,
       8.84046661, 1.92253241, 7.43681967, 7.49518592, 0.52650326])

In [102]:
# array of random numbers such that 1 <= x < 10
np.random.rand(10) * (10 - 1) + 1

array([6.00426795, 5.48467651, 8.70374485, 2.15692987, 4.18452817,
       7.82324979, 3.4373435 , 5.95960677, 1.156009  , 4.40670337])

##### Ex. array of random numbers such that 100 <= x < 200 ?

In [109]:
np.random.rand(100) * (200 - 100) + 100

array([190.49291941, 128.27285222, 134.60086945, 143.0118507 ,
       119.67989241, 119.46135842, 134.21333917, 124.56333933,
       140.33723008, 161.88782246, 135.26723326, 176.88585282,
       171.96619855, 100.0658776 , 150.28953062, 161.34895944,
       172.14843069, 153.62239868, 142.82528542, 166.83823946,
       127.61730961, 172.03413584, 158.09494893, 189.85035853,
       148.02889287, 163.16330716, 133.87318413, 164.57322017,
       163.86081151, 167.54063715, 141.97818634, 170.6233112 ,
       198.30222518, 191.24858712, 123.04197644, 190.08150807,
       130.6898975 , 112.57375015, 128.58769891, 150.46577372,
       124.81892214, 106.65776514, 198.22385465, 116.62918072,
       177.43870645, 158.26186899, 185.52485609, 113.4841224 ,
       108.71253218, 197.84936285, 169.62436668, 149.28644169,
       160.05118165, 123.07092255, 129.91257958, 154.28303649,
       141.49812248, 197.62703883, 115.33710958, 107.14374486,
       175.97167395, 192.12997539, 102.62988585, 140.56

In [110]:
# Fer-ho directament
# És un wrapper (funció que envolcalla una altre (la de abans))
np.random.uniform(10)

5.150036222500209

Distribucions de probabilitat, la més normal és la distribució uniforme, donat un proces estocastic, asigna la mateixa probabilitat a totes les seves possibles respostes (tirar un dau) &rarr; és un proccès estocastic amb 6 sortides amb la mateixa probabilitat (1/6). Distribució uniforme, si no ho apliquem no sobre un dau, sino sobre un interval. 

Cara o creu (0.5)

Podem fer diferents distribucions de probabilitat, canviar que surti més una cara que una altre.

#### nd-arrays

In [10]:
# 2d-array
x2d = np.array([[1, 3, 7, 2], [7, 8, 1, 5]])
x2d, x2d.shape

(array([[1, 3, 7, 2],
        [7, 8, 1, 5]]),
 (2, 4))

Un array de dos dimensions és una matriu. Canvia de pandas que es numpy i tindrà altres metodes

In [11]:
### 3d-array
x3d = np.array([[[8, 2, 3], [8, 2, 5], [3, 4, 2]]])
x3d, x3d.shape

(array([[[8, 2, 3],
         [8, 2, 5],
         [3, 4, 2]]]),
 (1, 3, 3))

In [12]:
### 3d-array
x3d = np.array([[[8, 2, 3], [8, 2, 5], [3, 4, 2]], [[7, 1, 2], [7, 1, 4], [2, 3, 1]]])
x3d, x3d.shape

(array([[[8, 2, 3],
         [8, 2, 5],
         [3, 4, 2]],
 
        [[7, 1, 2],
         [7, 1, 4],
         [2, 3, 1]]]),
 (2, 3, 3))

In [13]:
### 3d-array
x3d = np.array([[[8, 2, 3], [8, 2, 5], [3, 4, 2]], [[7, 1, 2], [7, 1, 4], [2, 3, 1]], [[6, 0, 1], [6, 0, 3], [1, 2, 0]] ])
x3d, x3d.shape

(array([[[8, 2, 3],
         [8, 2, 5],
         [3, 4, 2]],
 
        [[7, 1, 2],
         [7, 1, 4],
         [2, 3, 1]],
 
        [[6, 0, 1],
         [6, 0, 3],
         [1, 2, 0]]]),
 (3, 3, 3))

##### Ex. generate 3d-array of shape (3, 3, 4)

In [124]:
# Per formatejar i veure-ho bé, a sota per executar
x3d = np.array([
    [[8, 2, 3, 3], [8, 2, 5, 4], [3, 4, 2, 4]], 
    [[7, 1, 2, 4], [7, 1, 4, 4], [2, 3, 1, 4]], 
    [[6, 0, 1, 4], [6, 0, 3, 4], [1, 2, 0, 4]]
])
x3d.shape

(3, 3, 4)

##### Ex. generate 3d-array of shape (4, 3, 3)

In [125]:
x3d = np.array([
    [[8, 2, 3], [8, 2, 5], [3, 4, 2]], 
    [[7, 1, 2], [7, 1, 4], [2, 3, 1]],
    [[7, 1, 2], [7, 1, 4], [2, 3, 1]],
    [[6, 0, 1], [6, 0, 3], [1, 2, 0]]
])

In [126]:
x3d.shape

(4, 3, 3)

##### Ex. generate 3d-array of shape (3, 4, 3)

In [129]:
x3d = np.array([
    [[8, 2, 3], [8, 2, 5], [3, 4, 2], [3, 4, 2]], 
    [[7, 1, 2], [7, 1, 4], [2, 3, 1], [3, 4, 2]],
    [[6, 0, 1], [6, 0, 3], [1, 2, 0], [3, 4, 2]]
])
x3d.shape

(3, 4, 3)

#### array reshape functions

In [14]:
# 1d array
x1d = np.arange(24)
x1d, x1d.shape

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23]),
 (24,))

In [15]:
# 2d reshape
x2d = np.arange(24).reshape(6, 4)
x2d, x2d.shape

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]),
 (6, 4))

In [16]:
# 3d reshape
x3d = np.arange(24).reshape(3, 2, 4)
x3d, x3d.shape

(array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7]],
 
        [[ 8,  9, 10, 11],
         [12, 13, 14, 15]],
 
        [[16, 17, 18, 19],
         [20, 21, 22, 23]]]),
 (3, 2, 4))

In [17]:
# reshape view
x3d.reshape(2, 2, 6), x3d.shape

(array([[[ 0,  1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10, 11]],
 
        [[12, 13, 14, 15, 16, 17],
         [18, 19, 20, 21, 22, 23]]]),
 (3, 2, 4))

In [18]:
# reshape in place
x3d.shape = (4, 3, 2)
x3d, x3d.shape

(array([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],
 
        [[ 6,  7],
         [ 8,  9],
         [10, 11]],
 
        [[12, 13],
         [14, 15],
         [16, 17]],
 
        [[18, 19],
         [20, 21],
         [22, 23]]]),
 (4, 3, 2))

In [19]:
# flattened view (faster)
x3d.ravel(), x3d.shape

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23]),
 (4, 3, 2))

In [20]:
# flattened copy (slower)
x3d.flatten(), x3d.shape

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23]),
 (4, 3, 2))

#### Conditional functions

In [21]:
x = np.random.randint(1, 10, 20)
x

array([7, 6, 3, 7, 2, 8, 7, 1, 4, 1, 7, 3, 1, 8, 2, 3, 2, 9, 3, 2])

In [22]:
x > 5

array([ True,  True, False,  True, False,  True,  True, False, False,
       False,  True, False, False,  True, False, False, False,  True,
       False, False])

In [23]:
x[x > 5]

array([7, 6, 7, 8, 7, 7, 8, 9])

In [24]:
# position indexes
np.where(x > 5)

(array([ 0,  1,  3,  5,  6, 10, 13, 17], dtype=int64),)

In [25]:
# position values
x[np.where(x > 5)]

array([7, 6, 7, 8, 7, 7, 8, 9])

#### Conditional functions on two arrays

In [130]:
y = np.random.randint(1, 10, 20)
print("x")
print(x)
print("y")
print(y)
x, y

x
[7 6 3 7 2 8 7 1 4 1 7 3 1 8 2 3 2 9 3 2]
y
[1 4 4 9 2 2 6 7 8 5 6 7 7 4 1 7 3 2 5 3]


(array([7, 6, 3, 7, 2, 8, 7, 1, 4, 1, 7, 3, 1, 8, 2, 3, 2, 9, 3, 2]),
 array([1, 4, 4, 9, 2, 2, 6, 7, 8, 5, 6, 7, 7, 4, 1, 7, 3, 2, 5, 3]))

In [131]:
np.where(x < y, x, y) # retorna el més petit, sempre retorna un. x sigui més petit que y, retorna x sino y

array([1, 4, 3, 7, 2, 2, 6, 1, 4, 1, 6, 3, 1, 4, 1, 3, 2, 2, 3, 2])