### Numpy basics 1

- arrays: vectors and matrices
- slicing



In [1]:
import numpy as np

#### Arrays

In [2]:
# an array is a collection of numbers
np.array([3, 7, 1, 8, 3, 9])

array([3, 7, 1, 8, 3, 9])

#### Vectors

In [3]:
# a vector is an array where the elements are arranged in a single row
v = np.array([3, 7, 1, 8, 3, 9])
v

array([3, 7, 1, 8, 3, 9])

In [4]:
# length of a vector
len(v)

6

In [5]:
# shape of a vector
v.shape

(6,)

In [6]:
# get an element from a vector
v[3]

8

In [7]:
# set an element of a vector
v[3] = 12
v

array([ 3,  7,  1, 12,  3,  9])

#### Matrices

In [13]:
# a matrix is an array where the elements are arranged in several rows (or rows and columns)
m = np.array([[3, 7, 1], [8, 3, 9]])
m

array([[3, 7, 1],
       [8, 3, 9]])

In [9]:
# length of a matrix (!!)
len(m)

2

In [10]:
# size of a matrix: total number of elements
m.size

6

In [14]:
# shape of a matrix
m.shape

(2, 3)

In [15]:
# number of rows
m.shape[0]

2

In [16]:
# number of columns
m.shape[1]

3

In [14]:
# get an element of a matrix: (row, column) coordinates
m[1, 0]

8

In [17]:
# set an element of a matrix
m[1, 0] = 25
m

array([[ 3,  7,  1],
       [25,  3,  9]])

#### slicing

In [16]:
# vector
v

array([ 3,  7,  1, 12,  3,  9])

In [18]:
# front slice
v[:3]

array([3, 7, 1])

In [20]:
# back slice
v[2:5]

array([ 1, 12,  3])

In [21]:
# matrix
m

array([[ 3,  7,  1],
       [25,  3,  9]])

In [22]:
# row slicing
m[1, :]

array([25,  3,  9])

In [21]:
m[1]

array([25,  3,  9])

In [23]:
# column slicing
m[:, 2]

array([1, 9])

In [23]:
# slice
m[1:, 1:]

array([[3, 9]])

#### iterate on vectors/matrices

In [28]:
for x in v[3:]: print(x)

12
3
9


In [29]:
for row in m: print(row)

[3 7 1]
[25  3  9]


In [30]:
for row in m:
    print(row)
    for x in row:
        print(x)

[3 7 1]
3
7
1
[25  3  9]
25
3
9


#### iterate using indexes

In [27]:
for column_index in range(m.shape[1]): print(m[:, column_index])

[ 3 25]
[7 3]
[1 9]


In [28]:
for colIdx in range(m.shape[1]):
    print(m[:, colIdx])
    for rowIdx in range(m.shape[0]):
        print(m[rowIdx, colIdx])

[ 3 25]
3
25
[7 3]
7
3
[1 9]
1
9
